[[plugins]]
repo     = 'Shougo/dein.vim'

[[plugins]]
repo     = 'w0ng/vim-hybrid'
hook_add = '''
  set termguicolors
  set background=dark
  colorscheme hybrid
'''

[[plugins]]
repo     = 'frankier/neovim-colors-solarized-truecolor-only'
hook_add = '''
  set termguicolors
  set background=light
  colorscheme solarized
'''
if       = 0
