[[plugins]]
repo     = 'Shougo/deoplete.nvim'
on_i     = 1
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1

  let g:deoplete#sources = {}
  let g:deoplete#sources.php = ['file', 'buffer', 'dictionary']

  inoremap <silent><expr><CR>   pumvisible() ? deoplete#close_popup() : "\<CR>"
  inoremap <silent><expr><Up>   pumvisible() ? "\<C-p>"  : "\<Up>"
  inoremap <silent><expr><Down> pumvisible() ? "\<C-n>"  : "\<Down>"
'''

[[plugins]]
repo     = 'mattn/emmet-vim'
on_ft    = ['html', 'css', 'eruby']

[[plugins]]
repo     = 'tpope/vim-endwise'
on_ft    = ['ruby']
hook_add = '''
  let g:endwise_no_mappings = 0
'''

[[plugins]]
repo     = 'tpope/vim-rails'
on_ft    = ['ruby']

# ex: ft=vim
