[[plugins]]
repo     = 'Shougo/dein.vim'

[[plugins]]
repo     = 'w0ng/vim-hybrid'
hook_add = '''
  set termguicolors
  set background=dark
  colorscheme hybrid
'''

[[plugins]]
repo     = 'frankier/neovim-colors-solarized-truecolor-only'
hook_add = '''
  set termguicolors
  set background=light
  colorscheme solarized
'''
if       = 0

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  call denite#custom#var('file_rec', 'command',
    \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])

  call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#var('grep', 'default_opts',
    \ ['-i', '--vimgrep'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', [])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'final_opts', [])

  nnoremap [Denite] <Nop>
  nmap <Leader> [Denite]
  nnoremap <silent> [Denite]f :Denite file_rec<CR>
  nnoremap <silent> [Denite]b :Denite buffer<CR>
  call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>')
  call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>')
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
    \ 'colorscheme': 'wombat'
    \ }
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_enabled = 0
'''


# ex: ft=vim
