brew_prefix=$(brew --prefix)

# Source bash_prompt
if [ -f $brew_prefix/etc/bash_completion.d/git-prompt.sh ]; then
  . $brew_prefix/etc/bash_completion.d/git-prompt.sh
fi

# Source bash_completion
if [ -f $brew_prefix/etc/bash_completion ]; then
  . $brew_prefix/etc/bash_completion
fi

if [ -f $XDG_CONFIG_HOME/bash/alias ]; then
  . $XDG_CONFIG_HOME/bash/alias
fi
